### ISSUE TITLE
Set Up Shop

### ISSUE THREAD

**Issue by jalcine** [jalcine/wintermute-node#1]
In order to get this into a working state to use with the main repository; we'd need to do the following:
- [x] park the package on NPM
- [ ] [set up cmake-js build environment](https://github.com/jalcine/wintermute-node/issues/2) **#2**
- [ ] [set up test suite](https://github.com/jalcine/wintermute-node/issues/3) **#3**
- [ ] [enforce ABI checks for package with library](https://github.com/jalcine/wintermute-node/issues/4) **#4**

---

Blocks https://github.com/jalcine/wintermute/issues/9.
